app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls'))
]

app/menu/urls.py
from django.urls import path

from menu import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'category/<slug:parent_slug>/',
        views.menu_item,
        name='parent'
    ),
    path(
        'category/<slug:parent_slug>/<slug:child_slug>/',
        views.menu_item,
        name='child'
    ),
]

app/menu/models.py
from django.db import models


class Menu(models.Model):
    title = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Название'
    )
    slug = models.SlugField(
        max_length=50,
        unique=True,
        blank=True,
        null=True,
        verbose_name='Url',
    )
    parent = models.ForeignKey(
        to='self',
        on_delete=models.SET_DEFAULT,
        null=True,
        blank=True,
        related_name='child',
        verbose_name='Родитель',
        default=None
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'

app/menu/views.py
from django.shortcuts import render
from menu.models import Menu

def index(request):
    parent_menus = Menu.objects.filter(parent=None)
    return render(request, 'index.html', {'parent_menus': parent_menus})

def menu_item(request, parent_slug, child_slug=None):
    parent_menu = Menu.objects.get(slug=parent_slug)
    return render(request, 'index.html', {'parent_menu': parent_menu})

app/templates/index.html
{% load draw_menu %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tree Menu</title>
</head>
<body>
    <a href="/">Главная страница</a>
    <ul>
    {% for parent in parent_menus %}
        <li><a href="{% url 'menu:parent' parent.slug %}">{{ parent.title }}</a></li>
        <ul>
            {% for child in parent.child.all %}
                <li><a href="{% url 'menu:child' parent.slug child.slug %}">{{ child.title }}</a></li>
            {% endfor %}
        </ul>
    {% endfor %}
    </ul>
</body>
</html>